apiVersion: v1
kind: Service
metadata:
  name: kub-service
  labels:
    app: kub-service-label
spec:
  selector:
    app: kub-first-pod-label
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
